export type DriftStatus = "NORMAL" | "WARNING" | "CRITICAL";

export interface AIBriefRequest {
  corridor_id: string;
  corridor_name: string;
  drift_status: DriftStatus;
  risk_score: number;
  congestion_index: number;
  forecast: Array<{
    horizon_minutes: number;
    predicted_risk_score: number;
    predicted_congestion_index: number;
    confidence_score?: number;
  }>;
  active_interventions: Array<{
    intervention_id: string;
    status: "PENDING" | "APPROVED" | "REJECTED";
    proposed_action?: string;
    predicted_risk_delta?: number;
  }>;
  escalation_probability?: number;
}

export interface AIBriefResponseDriver {
  label: string;
  evidence: string;
}

export interface AIBriefResponseRecommendation {
  action: string;
  rationale: string;
  expected_impact: string;
}

export interface AIBriefResponse {
  executive_summary: string;
  drivers: AIBriefResponseDriver[];
  recommendation: AIBriefResponseRecommendation;
  caveats: string[];
  confidence: number;
}

export interface AIBriefError {
  error: string;
  code: "NO_API_KEY" | "CONTRACT_VIOLATION" | "LLM_ERROR" | "FEATURE_DISABLED" | "INVALID_REQUEST";
  correlation_id: string;
}

export const FALLBACK_BRIEF: AIBriefResponse = {
  executive_summary:
    "AI narrative generation is currently disabled. This corridor is operating under standard monitoring protocols. Review operational dashboard for current risk assessments and intervention status.",
  drivers: [
    {
      label: "Feature Status",
      evidence: "AI_NARRATIVE_ENABLED is set to false. Deterministic fallback is active.",
    },
  ],
  recommendation: {
    action: "Continue standard monitoring procedures",
    rationale: "AI-generated recommendations are not available in current configuration.",
    expected_impact: "No change to operational posture.",
  },
  caveats: [
    "This is a deterministic fallback response, not generated by AI.",
    "Enable AI_NARRATIVE_ENABLED to activate LLM-based briefings.",
  ],
  confidence: 1.0,
};
